---
- hosts: cloud
  remote_user: "{{ user }}"

  tasks:

    - name: build service
      become: yes 
      make:
        chdir: /home/{{ user }}/microservice-wordpress
        target: create

    - name: start service
      become: yes 
      make:
        chdir: /home/{{ user }}/microservice-wordpress
        target: start